# Generated by Django 5.1.6 on 2025-04-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmical_Core', '0003_likepost_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bannerimg',
            field=models.ImageField(default='static/images/profileimage.png', upload_to='banner_images'),
        ),
    ]
