# Generated by Django 5.1.6 on 2025-05-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmical_Core', '0006_reportedpost_threadmodel_messagemodel_savedpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadmodel',
            old_name='receiever',
            new_name='receiver',
        ),
    ]
